# PLUGIN CREER PAR Slayer && LotchMc GRATUIT !

# Pv ajouter
pv: 20

# Message après utilisation
heal-msg: "§6- §fHealStick utilisé §6-"

# Le cooldown en sec
cooldown: 15

# Message du cooldown
cooldown-msg: "Vous devez Vous devez attendre §6{time} secondes§f"